import os
import time
os.system('cls')
value = int(input("Enter the value: "))
unit1 = input("Enter its unit: ")
time.sleep(0.5)
os.system('cls')
print("Enter the value: "+str(value))
print("Enter its unit: metres")
print("sorry what was that - did you say metres?")
time.sleep(0.5)
unit2 = input("Enter the unit you would like to convert to: ")
time.sleep(0.5)
os.system('cls')
print("Enter the value: "+str(value))
print("Enter its unit: metres")
print("sorry what was that - did you say metres?")
print("Enter the unit you would like to convert to: micrometres")
print("sorry what was that - did you say micrometres?")
time.sleep(0.5)
print("Sorry for the inconvenience but this program will only convert from metres to micrometres\n")
micro_metres=value*1000000
time.sleep(1)
print(str(value),"metres =", micro_metres,"micrometres")